import type Database from "better-sqlite3";

const UP = `
CREATE TABLE IF NOT EXISTS tax_constants (
  id          INTEGER PRIMARY KEY,
  key         TEXT NOT NULL,
  value       INTEGER NOT NULL,
  unit        TEXT NOT NULL CHECK (unit IN ('pence', 'years', 'bps')),
  currency    TEXT,
  valid_from  DATE NOT NULL,
  valid_to    DATE,
  status      TEXT NOT NULL CHECK (status IN ('enacted', 'announced')),
  source      TEXT NOT NULL,
  note        TEXT,
  recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tax_constants_key ON tax_constants(key, valid_from);
`;

const DOWN = `
DROP INDEX IF EXISTS idx_tax_constants_key;
DROP TABLE IF EXISTS tax_constants;
`;

type Constant = {
  key: string;
  value: number;
  unit: "pence" | "years" | "bps";
  currency: string | null;
  valid_from: string;
  valid_to: string | null;
  status: "enacted" | "announced";
  source: string;
  note: string | null;
};

const ISA = "https://www.gov.uk/individual-savings-accounts";
const LISA = "https://www.gov.uk/lifetime-isa";
const FA2026 =
  "https://www.gov.uk/government/publications/changes-to-tax-rates-for-property-savings-and-dividend-income/change-to-tax-rates-for-property-savings-and-dividend-income-technical-note";
const PENSION =
  "https://www.gov.uk/government/publications/rates-and-allowances-pension-schemes/pension-schemes-rates";
const LSA = "https://www.gov.uk/tax-on-your-private-pension/lump-sum-allowance";
const NMPA = "https://www.legislation.gov.uk/ukpga/2022/3/section/10/enacted";
const SPA =
  "https://www.gov.uk/government/publications/state-pension-age-timetable/state-pension-age-timetable";
const INCOME_TAX_FREEZE =
  "https://www.gov.uk/government/publications/the-personal-allowance-and-basic-rate-limit-for-income-tax-and-certain-national-insurance-contributions-nics-thresholds-from-6-april-2026-to-5-apr/income-tax-personal-allowance-and-the-basic-rate-limit-and-certain-national-insurance-contributions-thresholds-from-6-april-2026-to-5-april-2028";
const EMPLOYER_RATES =
  "https://www.gov.uk/guidance/rates-and-thresholds-for-employers-2026-to-2027";
const CGT = "https://www.gov.uk/guidance/capital-gains-tax-rates-and-allowances";
const CGT_MIDYEAR =
  "https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual/cg10245";

const FREEZE_NOTE =
  "Threshold frozen; freeze extended to 5 Apr 2031 at Autumn 2025 Budget. Recorded as prose, not a separate announced row.";

const CONSTANTS: Constant[] = [
  {
    key: "isa_allowance",
    value: 2000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2017-04-06",
    valid_to: null,
    status: "enacted",
    source: ISA,
    note: "£20,000 overall ISA allowance; unchanged since 2017/18.",
  },
  {
    key: "cash_isa_allowance",
    value: 1200000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2027-04-06",
    valid_to: null,
    status: "enacted",
    source: FA2026,
    note: "£12,000 cash-ISA sub-limit within the £20,000 overall allowance (under-65s); over-65s retain £20,000. Future-effective from 6 Apr 2027.",
  },
  {
    key: "lisa_allowance",
    value: 400000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2017-04-06",
    valid_to: null,
    status: "enacted",
    source: LISA,
    note: "£4,000, counted within the £20,000 overall allowance.",
  },
  {
    key: "lisa_bonus_rate",
    value: 2500,
    unit: "bps",
    currency: null,
    valid_from: "2017-04-06",
    valid_to: null,
    status: "enacted",
    source: LISA,
    note: "25% government bonus on contributions.",
  },
  {
    key: "lisa_withdrawal_charge_rate",
    value: 2500,
    unit: "bps",
    currency: null,
    valid_from: "2021-04-06",
    valid_to: null,
    status: "enacted",
    source: LISA,
    note: "25% unauthorised-withdrawal charge (reverted from the temporary COVID 20%).",
  },

  {
    key: "pension_annual_allowance",
    value: 4000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2016-04-06",
    valid_to: "2023-04-05",
    status: "enacted",
    source: PENSION,
    note: "£40,000 (history).",
  },
  {
    key: "pension_annual_allowance",
    value: 6000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2023-04-06",
    valid_to: null,
    status: "enacted",
    source: PENSION,
    note: "£60,000 (current).",
  },
  {
    key: "pension_mpaa",
    value: 400000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2017-04-06",
    valid_to: "2023-04-05",
    status: "enacted",
    source: PENSION,
    note: "£4,000 money-purchase annual allowance (history).",
  },
  {
    key: "pension_mpaa",
    value: 1000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2023-04-06",
    valid_to: null,
    status: "enacted",
    source: PENSION,
    note: "£10,000 money-purchase annual allowance (current).",
  },
  {
    key: "pension_taper_threshold",
    value: 26000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2023-04-06",
    valid_to: null,
    status: "enacted",
    source: PENSION,
    note: "Adjusted income £260,000 — tapering of the annual allowance begins.",
  },
  {
    key: "pension_taper_floor",
    value: 20000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2023-04-06",
    valid_to: null,
    status: "enacted",
    source: PENSION,
    note: "Threshold income £200,000 — below this the taper does not apply.",
  },
  {
    key: "pension_min_tapered_allowance",
    value: 1000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2023-04-06",
    valid_to: null,
    status: "enacted",
    source: PENSION,
    note: "£10,000 minimum tapered annual allowance.",
  },
  {
    key: "pension_lump_sum_allowance",
    value: 26827500,
    unit: "pence",
    currency: "GBP",
    valid_from: "2024-04-06",
    valid_to: null,
    status: "enacted",
    source: LSA,
    note: "£268,275 lump sum allowance (lifetime allowance abolished).",
  },
  {
    key: "pension_access_age",
    value: 55,
    unit: "years",
    currency: null,
    valid_from: "2010-04-06",
    valid_to: "2028-04-05",
    status: "enacted",
    source: NMPA,
    note: "Normal minimum pension age (current).",
  },
  {
    key: "pension_access_age",
    value: 57,
    unit: "years",
    currency: null,
    valid_from: "2028-04-06",
    valid_to: null,
    status: "enacted",
    source: NMPA,
    note: "Normal minimum pension age rises to 57 (Finance Act 2022 s.10). Future-effective.",
  },
  {
    key: "state_pension_age",
    value: 66,
    unit: "years",
    currency: null,
    valid_from: "2020-10-06",
    valid_to: "2028-03-05",
    status: "enacted",
    source: SPA,
    note: "Reference default only. Real State Pension age is derived from date of birth, not a single age threshold; do not use for individual eligibility without DOB.",
  },
  {
    key: "state_pension_age",
    value: 67,
    unit: "years",
    currency: null,
    valid_from: "2028-03-06",
    valid_to: "2046-04-05",
    status: "enacted",
    source: SPA,
    note: "Reference default only; phased 2026-2028. Real State Pension age is date-of-birth driven, not a single age threshold.",
  },
  {
    key: "state_pension_age",
    value: 68,
    unit: "years",
    currency: null,
    valid_from: "2046-04-06",
    valid_to: null,
    status: "enacted",
    source: SPA,
    note: "Reference default only; phased 2044-2046, subject to statutory review. Real State Pension age is date-of-birth driven, not a single age threshold.",
  },

  {
    key: "personal_allowance",
    value: 1257000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: INCOME_TAX_FREEZE,
    note: `£12,570. ${FREEZE_NOTE}`,
  },
  {
    key: "personal_allowance_taper_threshold",
    value: 10000000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: INCOME_TAX_FREEZE,
    note: "Personal allowance taper begins at £100,000 of adjusted net income.",
  },
  {
    key: "personal_allowance_zero_at",
    value: 12514000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: INCOME_TAX_FREEZE,
    note: "Personal allowance fully tapered to nil at £125,140.",
  },
  {
    key: "basic_rate_limit",
    value: 3770000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: INCOME_TAX_FREEZE,
    note: `Basic-rate band width £37,700. ${FREEZE_NOTE}`,
  },
  {
    key: "higher_rate_threshold",
    value: 5027000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: INCOME_TAX_FREEZE,
    note: "£50,270 (personal allowance + basic-rate limit).",
  },
  {
    key: "additional_rate_threshold",
    value: 12514000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: INCOME_TAX_FREEZE,
    note: "£125,140 — additional rate applies above this.",
  },
  {
    key: "income_tax_basic_rate",
    value: 2000,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: "https://www.gov.uk/income-tax-rates",
    note: "20% basic rate (rUK).",
  },
  {
    key: "income_tax_higher_rate",
    value: 4000,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: "https://www.gov.uk/income-tax-rates",
    note: "40% higher rate (rUK).",
  },
  {
    key: "income_tax_additional_rate",
    value: 4500,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: "https://www.gov.uk/income-tax-rates",
    note: "45% additional rate (rUK).",
  },

  {
    key: "ni_primary_threshold",
    value: 1257000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: EMPLOYER_RATES,
    note: "£12,570 Class 1 primary threshold (employee).",
  },
  {
    key: "ni_upper_earnings_limit",
    value: 5027000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: EMPLOYER_RATES,
    note: "£50,270 upper earnings limit.",
  },
  {
    key: "ni_employee_main_rate",
    value: 800,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: EMPLOYER_RATES,
    note: "8% employee main rate (primary threshold to upper earnings limit).",
  },
  {
    key: "ni_employee_upper_rate",
    value: 200,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: EMPLOYER_RATES,
    note: "2% employee rate above the upper earnings limit.",
  },
  {
    key: "ni_secondary_threshold",
    value: 500000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: EMPLOYER_RATES,
    note: "£5,000 secondary threshold (employer).",
  },
  {
    key: "ni_employer_rate",
    value: 1500,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: EMPLOYER_RATES,
    note: "15% employer secondary Class 1 rate.",
  },

  {
    key: "cgt_annual_exempt_amount",
    value: 1230000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2022-04-06",
    valid_to: "2023-04-05",
    status: "enacted",
    source: CGT,
    note: "£12,300 (history).",
  },
  {
    key: "cgt_annual_exempt_amount",
    value: 600000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2023-04-06",
    valid_to: "2024-04-05",
    status: "enacted",
    source: CGT,
    note: "£6,000 (history).",
  },
  {
    key: "cgt_annual_exempt_amount",
    value: 300000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2024-04-06",
    valid_to: null,
    status: "enacted",
    source: CGT,
    note: "£3,000 (current, fixed).",
  },
  {
    key: "cgt_rate_lower",
    value: 1000,
    unit: "bps",
    currency: null,
    valid_from: "2016-04-06",
    valid_to: "2024-10-29",
    status: "enacted",
    source: CGT_MIDYEAR,
    note: "10% basic-rate-band CGT (history).",
  },
  {
    key: "cgt_rate_lower",
    value: 1800,
    unit: "bps",
    currency: null,
    valid_from: "2024-10-30",
    valid_to: null,
    status: "enacted",
    source: CGT_MIDYEAR,
    note: "18% basic-rate-band CGT (mid-year change from 30 Oct 2024).",
  },
  {
    key: "cgt_rate_higher",
    value: 2000,
    unit: "bps",
    currency: null,
    valid_from: "2016-04-06",
    valid_to: "2024-10-29",
    status: "enacted",
    source: CGT_MIDYEAR,
    note: "20% higher-rate CGT (history).",
  },
  {
    key: "cgt_rate_higher",
    value: 2400,
    unit: "bps",
    currency: null,
    valid_from: "2024-10-30",
    valid_to: null,
    status: "enacted",
    source: CGT_MIDYEAR,
    note: "24% higher-rate CGT (from 30 Oct 2024).",
  },
  {
    key: "cgt_rate_residential_lower",
    value: 1800,
    unit: "bps",
    currency: null,
    valid_from: "2024-04-06",
    valid_to: null,
    status: "enacted",
    source: CGT,
    note: "18% CGT on residential property (basic-rate band).",
  },
  {
    key: "cgt_rate_residential_higher",
    value: 2400,
    unit: "bps",
    currency: null,
    valid_from: "2024-04-06",
    valid_to: null,
    status: "enacted",
    source: CGT,
    note: "24% CGT on residential property (higher rate).",
  },
  {
    key: "dividend_allowance",
    value: 100000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2023-04-06",
    valid_to: "2024-04-05",
    status: "enacted",
    source: CGT,
    note: "£1,000 dividend allowance (history).",
  },
  {
    key: "dividend_allowance",
    value: 50000,
    unit: "pence",
    currency: "GBP",
    valid_from: "2024-04-06",
    valid_to: null,
    status: "enacted",
    source: CGT,
    note: "£500 dividend allowance (current).",
  },
  {
    key: "dividend_rate_ordinary",
    value: 875,
    unit: "bps",
    currency: null,
    valid_from: "2023-04-06",
    valid_to: "2026-04-05",
    status: "enacted",
    source: FA2026,
    note: "8.75% ordinary dividend rate (history).",
  },
  {
    key: "dividend_rate_ordinary",
    value: 1075,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: FA2026,
    note: "10.75% ordinary dividend rate (raised, Finance Act 2026).",
  },
  {
    key: "dividend_rate_upper",
    value: 3375,
    unit: "bps",
    currency: null,
    valid_from: "2023-04-06",
    valid_to: "2026-04-05",
    status: "enacted",
    source: FA2026,
    note: "33.75% upper dividend rate (history).",
  },
  {
    key: "dividend_rate_upper",
    value: 3575,
    unit: "bps",
    currency: null,
    valid_from: "2026-04-06",
    valid_to: null,
    status: "enacted",
    source: FA2026,
    note: "35.75% upper dividend rate (raised, Finance Act 2026).",
  },
  {
    key: "dividend_rate_additional",
    value: 3935,
    unit: "bps",
    currency: null,
    valid_from: "2023-04-06",
    valid_to: null,
    status: "enacted",
    source: FA2026,
    note: "39.35% additional dividend rate (unchanged).",
  },
];

export function up(db: Database.Database): void {
  db.exec(UP);
  const insert = db.prepare(
    `INSERT INTO tax_constants
       (key, value, unit, currency, valid_from, valid_to, status, source, note)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  );
  for (const c of CONSTANTS) {
    insert.run(
      c.key,
      c.value,
      c.unit,
      c.currency,
      c.valid_from,
      c.valid_to,
      c.status,
      c.source,
      c.note,
    );
  }
}

export function down(db: Database.Database): void {
  db.exec(DOWN);
}
