import type { NetWorthResult } from "../net_worth/types.js";
import type { CashflowResult } from "../cashflow/types.js";
import type { MonthCoverage } from "../net_worth/coverage.js";
import type { ClassFreshness, ClassOutcome } from "../core/freshness.js";
import type { IngestReviewResult } from "../tools/ingest_document.js";
import type { Directive } from "../ui/goals_section.js";
import type { WalletDiscovery } from "../ui/connectors/ethereum.js";

const coverage: MonthCoverage[] = [
  {
    month: 4,
    year: 2026,
    initial: "A",
    state: "incomplete",
    fraction_fresh: 0.5,
    series: [
      { label: "Accounts", state: "stale", age_days: 227 },
      { label: "Pension", state: "stale", age_days: 425 },
      { label: "Investments", state: "stale", age_days: 272 },
      { label: "Property", state: "fresh", age_days: 60 },
      { label: "Mortgage", state: "fresh", age_days: 60 },
      { label: "Payslip", state: "fresh", age_days: 5 },
    ],
  },
  {
    month: 5,
    year: 2026,
    initial: "M",
    state: "incomplete",
    fraction_fresh: 0.5,
    series: [
      { label: "Accounts", state: "stale", age_days: 258 },
      { label: "Pension", state: "stale", age_days: 456 },
      { label: "Investments", state: "stale", age_days: 303 },
      { label: "Property", state: "fresh", age_days: 30 },
      { label: "Mortgage", state: "fresh", age_days: 30 },
      { label: "Payslip", state: "fresh", age_days: 6 },
    ],
  },
  {
    month: 6,
    year: 2026,
    initial: "J",
    state: "current",
    fraction_fresh: 0.34,
    series: [
      { label: "Accounts", state: "stale", age_days: 269 },
      { label: "Pension", state: "stale", age_days: 467 },
      { label: "Investments", state: "stale", age_days: 314 },
      { label: "Property", state: "fresh", age_days: 41 },
      { label: "Mortgage", state: "fresh", age_days: 41 },
      { label: "Payslip", state: "missing", age_days: null },
    ],
  },
  { month: 7, year: 2026, initial: "J", state: "future", fraction_fresh: 0, series: [] },
  { month: 8, year: 2026, initial: "A", state: "future", fraction_fresh: 0, series: [] },
  { month: 9, year: 2026, initial: "S", state: "future", fraction_fresh: 0, series: [] },
  { month: 10, year: 2026, initial: "O", state: "future", fraction_fresh: 0, series: [] },
  { month: 11, year: 2026, initial: "N", state: "future", fraction_fresh: 0, series: [] },
  { month: 12, year: 2026, initial: "D", state: "future", fraction_fresh: 0, series: [] },
  { month: 1, year: 2027, initial: "J", state: "future", fraction_fresh: 0, series: [] },
  { month: 2, year: 2027, initial: "F", state: "future", fraction_fresh: 0, series: [] },
  { month: 3, year: 2027, initial: "M", state: "future", fraction_fresh: 0, series: [] },
];

const freshness: ClassFreshness[] = [
  {
    class: "monzo",
    connected: true,
    last_at: "2026-06-11",
    age_seconds: 1800,
    ttl_seconds: 86400,
    is_stale: false,
  },
  {
    class: "prices",
    connected: true,
    last_at: "2026-06-11",
    age_seconds: 900,
    ttl_seconds: 3600,
    is_stale: false,
  },
  {
    class: "ethereum",
    connected: true,
    last_at: "2026-06-11",
    age_seconds: 3600,
    ttl_seconds: 86400,
    is_stale: false,
  },
];

const netWorth: NetWorthResult = {
  as_of: "2026-06-11",
  realised: [
    {
      kind: "account",
      name: "Barclays Premier Current Account",
      institution: "Barclays",
      value_pence: 487650,
      valid_from: "2026-05-01",
      recorded_at: "2026-06-11",
      source_id: 12,
      currency: "GBP",
    },
    {
      kind: "account",
      name: "Nationwide Instant Access Saver",
      institution: "Nationwide",
      value_pence: 2800000,
      valid_from: "2026-05-05",
      recorded_at: "2026-06-11",
      source_id: 19,
      currency: "GBP",
    },
    {
      kind: "account",
      name: "Vanguard Stocks & Shares ISA",
      institution: "Vanguard",
      value_pence: 15495000,
      valid_from: "2026-05-10",
      recorded_at: "2026-06-11",
      source_id: 24,
      currency: "GBP",
    },
    {
      kind: "account",
      name: "Monzo Joint",
      institution: "Monzo",
      value_pence: 84500,
      valid_from: "2025-09-15",
      recorded_at: "2026-06-11",
      source_id: 25,
      currency: "GBP",
    },
    {
      kind: "pension",
      name: "Aviva Workplace Pension — Salary Sacrifice",
      institution: "Aviva",
      value_pence: 19810000,
      valid_from: "2026-05-20",
      recorded_at: "2026-06-11",
      source_id: 30,
      currency: "GBP",
    },
    {
      kind: "pension",
      name: "Old Employer SIPP (Fidelity)",
      institution: "Fidelity",
      value_pence: 2340000,
      valid_from: "2025-03-01",
      recorded_at: "2026-06-11",
      source_id: 31,
      currency: "GBP",
    },
    {
      kind: "property",
      name: "Nationwide — 12 Acacia Avenue",
      value_pence: 84000000,
      valid_from: "2026-05-01",
      recorded_at: "2026-06-11",
      source_id: 43,
      currency: "GBP",
      price_as_of: "2026-05-01",
      price_source: "manual",
    },
    {
      kind: "mortgage",
      name: "Nationwide — 12 Acacia Avenue",
      value_pence: -27410000,
      valid_from: "2026-05-01",
      recorded_at: "2026-06-11",
      source_id: 43,
      currency: "GBP",
    },
    {
      kind: "asset",
      name: "ETH",
      value_pence: 1190000,
      valid_from: "2026-05-25",
      recorded_at: "2026-06-11",
      source_id: 44,
      currency: "GBP",
      ticker: "ETH",
      quantity: 425000000,
      quantity_scale: 100000000,
      unit_price_pence: 280000,
      price_as_of: "2026-06-11",
      price_source: "coingecko",
    },
    {
      kind: "asset",
      name: "Vanguard FTSE All-World UCITS ETF (Acc)",
      value_pence: 3520000,
      valid_from: "2026-04-12",
      recorded_at: "2026-06-11",
      source_id: 48,
      currency: "GBP",
      ticker: "VWRP",
      quantity: 320,
      quantity_scale: 1,
      unit_price_pence: 11000,
      price_as_of: "2026-06-11",
      price_source: "yahoo",
    },
    {
      kind: "asset",
      name: "AAPL",
      value_pence: 684990,
      valid_from: "2026-03-08",
      recorded_at: "2026-06-11",
      source_id: 50,
      currency: "GBP",
      ticker: "AAPL",
      quantity: 45,
      quantity_scale: 1,
      unit_price_pence: 15222,
      price_as_of: "2025-11-30",
      price_source: "yahoo",
    },
    {
      kind: "asset",
      name: "NS&I Premium Bonds",
      value_pence: 5000000,
      valid_from: "2025-08-01",
      recorded_at: "2025-08-01",
      source_id: 52,
      currency: "GBP",
      ticker: null,
      quantity: 1,
      quantity_scale: 1,
      unit_price_pence: 5000000,
      price_as_of: "2025-08-01",
      price_source: "manual",
    },
  ],
  realised_total_pence: 108002140,
  contingent: [
    {
      grant_id: 1,
      vest_date: "2026-08-01",
      scheme_type: "rsu",
      units: 500,
      ticker: "ACME",
      asset_name: "ACME Corp",
      price_per_unit_pence: 4250,
      price_as_of: "2026-05-28",
      price_source: "manual",
      strike_pence: null,
      monthly_contribution_pence: null,
      savings_floor_pence: null,
      projected_value_pence: 2125000,
      not_owned: true,
    },
    {
      grant_id: 3,
      vest_date: "2026-09-01",
      scheme_type: "unapproved",
      units: 1000,
      ticker: "ACME",
      asset_name: "ACME Corp",
      price_per_unit_pence: 4250,
      price_as_of: "2026-05-28",
      price_source: "manual",
      strike_pence: 1200,
      monthly_contribution_pence: null,
      savings_floor_pence: null,
      projected_value_pence: 3050000,
      not_owned: true,
    },
    {
      grant_id: 2,
      vest_date: "2026-11-01",
      scheme_type: "emi",
      units: 2500,
      ticker: "ACME",
      asset_name: "ACME Corp",
      price_per_unit_pence: 4250,
      price_as_of: "2026-05-28",
      price_source: "manual",
      strike_pence: 50,
      monthly_contribution_pence: null,
      savings_floor_pence: null,
      projected_value_pence: 10500000,
      not_owned: true,
    },
    {
      grant_id: 1,
      vest_date: "2027-02-01",
      scheme_type: "rsu",
      units: 500,
      ticker: "ACME",
      asset_name: "ACME Corp",
      price_per_unit_pence: 4250,
      price_as_of: "2026-05-28",
      price_source: "manual",
      strike_pence: null,
      monthly_contribution_pence: null,
      savings_floor_pence: null,
      projected_value_pence: 2125000,
      not_owned: true,
    },
    {
      grant_id: 4,
      vest_date: "2027-06-01",
      scheme_type: "rsu",
      units: 750,
      ticker: null,
      asset_name: "Borealis Dynamics Employee Equity Plan",
      price_per_unit_pence: null,
      price_as_of: null,
      price_source: null,
      strike_pence: null,
      monthly_contribution_pence: null,
      savings_floor_pence: null,
      projected_value_pence: null,
      not_owned: true,
    },
    {
      grant_id: 3,
      vest_date: "2027-09-01",
      scheme_type: "unapproved",
      units: 1000,
      ticker: "ACME",
      asset_name: "ACME Corp",
      price_per_unit_pence: 4250,
      price_as_of: "2026-05-28",
      price_source: "manual",
      strike_pence: 1200,
      monthly_contribution_pence: null,
      savings_floor_pence: null,
      projected_value_pence: 3050000,
      not_owned: true,
    },
    {
      grant_id: 5,
      vest_date: "2028-03-01",
      scheme_type: "saye",
      units: 880,
      ticker: "ACME",
      asset_name: "ACME Corp",
      price_per_unit_pence: 4250,
      price_as_of: "2026-05-28",
      price_source: "manual",
      strike_pence: 4400,
      monthly_contribution_pence: 50000,
      savings_floor_pence: 1800000,
      projected_value_pence: 1800000,
      not_owned: true,
    },
    {
      grant_id: 2,
      vest_date: "2028-11-01",
      scheme_type: "emi",
      units: 2500,
      ticker: "ACME",
      asset_name: "ACME Corp",
      price_per_unit_pence: 4250,
      price_as_of: "2026-05-28",
      price_source: "manual",
      strike_pence: 50,
      monthly_contribution_pence: null,
      savings_floor_pence: null,
      projected_value_pence: 10500000,
      not_owned: true,
    },
  ],
  contingent_total_pence: 35275000,
  contingent_unscheduled: [
    {
      grant_id: 9,
      scheme_type: "rsu",
      units: 350,
      ticker: "ACME",
      asset_name: "ACME Corp",
    },
  ],
  unknown: [],
  trend: [
    { date: "2025-07-01", realised_total_pence: 74025900 },
    { date: "2025-08-01", realised_total_pence: 79150220 },
    { date: "2025-09-01", realised_total_pence: 80781460 },
    { date: "2025-10-01", realised_total_pence: 84869840 },
    { date: "2025-11-01", realised_total_pence: 86211600 },
    { date: "2025-12-01", realised_total_pence: 88046550 },
    { date: "2026-01-01", realised_total_pence: 91143400 },
    { date: "2026-02-01", realised_total_pence: 91175950 },
    { date: "2026-03-01", realised_total_pence: 95279700 },
    { date: "2026-04-01", realised_total_pence: 99811820 },
    { date: "2026-05-01", realised_total_pence: 104347140 },
    { date: "2026-06-01", realised_total_pence: 108002140 },
  ],
  coverage,
  freshness,
};

const briefingDirectives: Directive[] = [
  {
    goal_id: 1,
    goal_type: "emergency_fund",
    sub_goal: "fund_target",
    kind: "progress",
    message:
      "Emergency fund holds £28,000.00 of the £33,600.00 target — 83% funded across Nationwide Instant Access Saver.",
    data: { current_pence: 2800000, target_pence: 3360000, pct: 83 },
  },
  {
    goal_id: 1,
    goal_type: "emergency_fund",
    sub_goal: "fund_target",
    kind: "data_gap",
    message:
      "Monthly essential spending is estimated from only two months of Monzo history; the target may shift as more months arrive.",
    data: { months_observed: 2 },
  },
  {
    goal_id: 2,
    goal_type: "isa_max",
    sub_goal: "allowance_used",
    kind: "progress",
    message:
      "ISA contributions stand at £12,500.00 of the £20,000.00 annual allowance for 2026/27.",
    data: { used_pence: 1250000, allowance_pence: 2000000, tax_year: "2026/27" },
  },
  {
    goal_id: 2,
    goal_type: "isa_max",
    sub_goal: "allowance_used",
    kind: "deadline",
    message: "£7,500.00 of ISA allowance remains; the window closes on 5 April 2027.",
    data: { remaining_pence: 750000, deadline: "2027-04-05" },
  },
];

const briefing = {
  as_of: "2026-06-11",
  directives: briefingDirectives,
};

const cashflow: CashflowResult = {
  tax_year: "2026/27",
  period_start: "2026-04-06",
  period_end: "2027-04-05",
  income: {
    net_pence: 904100,
    gross_pence: 1240000,
    paye_pence: 247900,
    ni_employee_pence: 44000,
    pension_employee_pence: 28000,
    pension_employer_pence: 14000,
    other_deductions_pence: 16000,
    tax_code: "1257L",
    payslip_count: 2,
    line_items: [
      { description: "Basic Salary", section: "payment", amount_pence: 1190000 },
      {
        description: "On-call Allowance (June rotation)",
        section: "payment",
        amount_pence: 50000,
      },
      { description: "PAYE", section: "deduction", amount_pence: 247900 },
      { description: "National Insurance", section: "deduction", amount_pence: 44000 },
      {
        description: "Salary Sacrifice Pension — Employer Matched",
        section: "deduction",
        amount_pence: 28000,
      },
      {
        description: "Private Medical Insurance (BUPA family cover)",
        section: "deduction",
        amount_pence: 9000,
      },
      { description: "Gym Membership", section: "deduction", amount_pence: 7000 },
    ],
  },
  transactions_by_category: [
    {
      category: "groceries",
      inflow_pence: 0,
      outflow_pence: 122900,
      count: 14,
      samples: ["Sainsbury's Local Clapham High St", "Waitrose & Partners"],
    },
    {
      category: "bills",
      inflow_pence: 0,
      outflow_pence: 95599,
      count: 6,
      samples: ["EDF Energy Direct Debit", "Thames Water"],
    },
    {
      category: "holiday_japan_2027",
      inflow_pence: 0,
      outflow_pence: 84050,
      count: 3,
      samples: ["Japan Airlines Intl Booking", "Airbnb Tokyo Shinjuku"],
    },
    {
      category: "eating_out",
      inflow_pence: 0,
      outflow_pence: 52400,
      count: 9,
      samples: ["Dishoom Covent Garden", "Franco Manca"],
    },
    {
      category: "transport",
      inflow_pence: 0,
      outflow_pence: 31200,
      count: 18,
      samples: ["TfL Travel Charge", "Uber"],
    },
    {
      category: "subscriptions",
      inflow_pence: 0,
      outflow_pence: 12397,
      count: 5,
      samples: ["Spotify", "Netflix", "iCloud Storage"],
    },
    {
      category: "general",
      inflow_pence: 4350,
      outflow_pence: 28733,
      count: 11,
      samples: ["Amazon Marketplace", "Boots"],
    },
  ],
  income_by_source: [
    { source: "ACME INDUSTRIES PAYROLL (BACS)", inflow_pence: 1808200, count: 2 },
    { source: "HMRC Child Benefit", inflow_pence: 17050, count: 2 },
    { source: "Vinted marketplace sales", inflow_pence: 4350, count: 3 },
  ],
  transaction_inflow_total_pence: 1829600,
  transaction_outflow_total_pence: 427279,
  income_total_pence: 1808200,
  spending_total_pence: 427279,
  pot_savings_net_pence: 150000,
  net_cashflow_pence: 1230921,
  trend: [
    {
      month: "2025-07",
      transaction_inflow_pence: 893200,
      transaction_outflow_pence: 412765,
      net_pence: 480435,
    },
    {
      month: "2025-08",
      transaction_inflow_pence: 901450,
      transaction_outflow_pence: 538291,
      net_pence: 363159,
    },
    {
      month: "2025-09",
      transaction_inflow_pence: 893200,
      transaction_outflow_pence: 391044,
      net_pence: 502156,
    },
    {
      month: "2025-10",
      transaction_inflow_pence: 1093200,
      transaction_outflow_pence: 470213,
      net_pence: 622987,
    },
    {
      month: "2025-11",
      transaction_inflow_pence: 893200,
      transaction_outflow_pence: 612908,
      net_pence: 280292,
    },
    {
      month: "2025-12",
      transaction_inflow_pence: 953200,
      transaction_outflow_pence: 781426,
      net_pence: 171774,
    },
    {
      month: "2026-01",
      transaction_inflow_pence: 893200,
      transaction_outflow_pence: 350912,
      net_pence: 542288,
    },
    {
      month: "2026-02",
      transaction_inflow_pence: 893200,
      transaction_outflow_pence: 402387,
      net_pence: 490813,
    },
    {
      month: "2026-03",
      transaction_inflow_pence: 1493200,
      transaction_outflow_pence: 455671,
      net_pence: 1037529,
    },
    {
      month: "2026-04",
      transaction_inflow_pence: 914800,
      transaction_outflow_pence: 423106,
      net_pence: 491694,
    },
    {
      month: "2026-05",
      transaction_inflow_pence: 914800,
      transaction_outflow_pence: 427279,
      net_pence: 487521,
    },
    {
      month: "2026-06",
      transaction_inflow_pence: 304500,
      transaction_outflow_pence: 158211,
      net_pence: 146289,
    },
  ],
  coverage,
  freshness,
};

const ingestReview: IngestReviewResult = {
  review_id: "rev_01HZXK4Q8N",
  filename: "2026-05_payslip_acme_industries_maximilian_richardson.pdf",
  parsed: {
    pay_date: "2026-05-28",
    tax_year: "2026/27",
    tax_code: "1257L",
    gross_pence: 620000,
    taxable_pence: 578000,
    net_pence: 452050,
    paye_pence: 123950,
    ni_employee_pence: 22000,
    pension_employee_pence: 14000,
    pension_employer_pence: 7000,
  },
  payload: {
    line_items: [
      { description: "Basic Salary", section: "payment", amount_pence: 595000 },
      {
        description: "On-call Allowance (May rotation)",
        section: "payment",
        amount_pence: 25000,
      },
      { description: "PAYE", section: "deduction", amount_pence: 123950 },
      { description: "National Insurance", section: "deduction", amount_pence: 22000 },
      {
        description: "Salary Sacrifice Pension — Employer Matched",
        section: "deduction",
        amount_pence: 14000,
      },
      {
        description: "Private Medical Insurance (BUPA family cover)",
        section: "deduction",
        amount_pence: 4500,
      },
    ],
  },
};

const walletDiscovery: WalletDiscovery = {
  address: "0x4bbeEB066eD09B7AEd07bF39EEe0460DFa261520",
  assets: [
    {
      kind: "native",
      symbol: "ETH",
      name: "Ether",
      contract_address: null,
      decimals: 18,
      raw_balance: "4250000000000000000",
      display_balance: "4.25",
    },
    {
      kind: "token",
      symbol: "wstETH",
      name: "Wrapped liquid staked Ether 2.0",
      contract_address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0",
      decimals: 18,
      raw_balance: "1875421390041287465",
      display_balance: "1.875421390041287465",
    },
    {
      kind: "token",
      symbol: "USDC",
      name: "USD Coin",
      contract_address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      decimals: 6,
      raw_balance: "12500430000",
      display_balance: "12,500.43",
    },
    {
      kind: "token",
      symbol: "UNI",
      name: "Uniswap Protocol Governance Token",
      contract_address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
      decimals: 18,
      raw_balance: "310500000000000000000",
      display_balance: "310.5",
    },
    {
      kind: "token",
      symbol: "AAVE",
      name: "Aave Token",
      contract_address: "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
      decimals: 18,
      raw_balance: "12000000000000000000",
      display_balance: "12.0",
    },
  ],
  transfers_capped: true,
};

const refreshOutcomes: ClassOutcome[] = [
  { class: "monzo", was_stale: true, action: "refreshed" },
  { class: "prices", was_stale: true, action: "refreshed" },
  { class: "ethereum", was_stale: false, action: "skipped_fresh" },
];

const textResults: Record<string, string> = {
  confirm_staged_rows:
    "Saved 6 rows from 2026-05_payslip_acme_industries_maximilian_richardson.pdf to the ledger. Pay date 2026-05-28, gross £6,200.00, net £4,520.50.",
  connect_monzo:
    "Monzo connected. Backfilled 412 transactions across 2 accounts and 3 pots, from 2025-07-02 to today.",
  sync_monzo:
    "Synced 28 new transactions across Monzo Current and Monzo Joint. Balances updated as of 2026-06-11 09:42 UTC.",
  connect_ethereum:
    "Imported 5 holdings from 0x4bbe…1520. ETH, wstETH, USDC, UNI and AAVE will be valued on each price sync.",
  sync_ethereum:
    "Ethereum wallet synced. 5 balances refreshed from chain state as of block 22,841,003.",
};

const jsonResults: Record<string, unknown> = {
  get_net_worth: netWorth,
  get_briefing: briefing,
  get_cashflow: cashflow,
  refresh_stale_data: refreshOutcomes,
  ingest_document: ingestReview,
  discover_ethereum_wallet: walletDiscovery,
};

export function fixtureResult(toolName: string): {
  content: { type: "text"; text: string }[];
} {
  const json = jsonResults[toolName];
  const text = json !== undefined ? JSON.stringify(json) : textResults[toolName];
  if (text === undefined) {
    throw new Error(`No fixture for tool ${toolName}.`);
  }
  return { content: [{ type: "text", text }] };
}
